spring:
  cloud:
    gateway:
      routes:
        - id: signup_route
          uri: http://localhost:8080
          predicates:
            - Path=/signup/**
            - Method=POST
        - id: login_route
          uri: http://localhost:8080
          predicates:
            - Path=/login/**
            - Method=POST
        - id: project_api
          uri: http://localhost:8081
          predicates:
            - Path=/project/**
          filters:
            - RewritePath=/project/(?<path>.*), /v1/api/project/$\{path}
            - name: JwtVerificationFilter
  profiles:
    include: key
server:
  port: 9000
